# for test environment
spring:
  application:
    name: #projectName
  profiles: test
  boot:
    admin:
      url: http://ali-hz-hbase-name-node:12309
      username: mobvoi
      password: mobvoi
  gson:
    converter:
      enable: false
endpoints:
  sensitive: false
server:
  port: 8080

#common-data-starter-jdbc-settings
#common-data-starter-kylin-jdbc-settings
#common-data-starter-cache-settings
#common-data-starter-kafka-settings