# for prod environment
spring:
  application:
    name: #projectName
  profiles: prod
  boot:
    admin:
      url: http://spring-boot-admin
      username: mobvoi
      password: mobvoi
  gson:
    converter:
      enable: false
endpoints:
  sensitive: false
server:
  port: 8080

#common-data-starter-jdbc-settings
#common-data-starter-kylin-jdbc-settings
#common-data-starter-cache-settings
#common-data-starter-kafka-settings